name: Build API

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/loumonthjack/resumed-events

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SSH to Host
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          AWS_HOSTNAME: ${{ secrets.AWS_HOSTNAME }}
          AWS_USERNAME: ${{ secrets.AWS_USERNAME  }}

        run: |
          echo "$AWS_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${AWS_USERNAME}@${AWS_HOSTNAME} '

            # 📌 Start your instance/server related tasks form here.
            sudo -i
            pwd
            cd /home/app/resumed-events 
            chown -R $(whoami):$(whoami) /home/app/resumed-events
            git pull
            npx prisma db push
          '