
name: Build API

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/loumonthjack/resumed-events

jobs:
  deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
    
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
    
        - name: Build, tag, and push image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: resumed-events
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        - name: Replace environment variables in task definition
          run: |
              sed -i "s#{{VAR_1}}#${{ secrets.NODE_ENV }}#g" ${{ github.workspace }}/ecs-task-def.json
              sed -i "s#{{VAR_2}}#${{ secrets.PORT }}#g" ${{ github.workspace }}/ecs-task-def.json
              sed -i "s#{{VAR_3}}#${{ secrets.DATABASE_URL }}#g" ${{ github.workspace }}/ecs-task-def.json
              sed -i "s#{{VAR_4}}#${{ secrets.JWT_SECRET_KEY }}#g" ${{ github.workspace }}/ecs-task-def.json
              sed -i "s#{{VAR_5}}#${{ secrets.STRIPE_WEBHOOK_KEY_TEST }}#g" ${{ github.workspace }}/ecs-task-def.json
              sed -i "s#{{VAR_6}}#${{ secrets.STRIPE_SECRET_KEY_TEST }}#g" ${{ github.workspace }}/ecs-task-def.json
              sed -i "s#{{VAR_7}}#${{ secrets.SENDGRID_API_KEY }}#g" ${{ github.workspace }}/ecs-task-def.json
              sed -i "s#{{VAR_8}}#${{ secrets.SENDGRID_FROM_EMAIL }}#g" ${{ github.workspace }}/ecs-task-def.json
              sed -i "s#{{VAR_9}}#${{ secrets.AWS_BUCKET_NAME }}#g" ${{ github.workspace }}/ecs-task-def.json
              sed -i "s#{{VAR_10}}#${{ secrets.AWS_ACCESS_KEY_ID }}#g" ${{ github.workspace }}/ecs-task-def.json
              sed -i "s#{{VAR_11}}#${{ secrets.AWS_SECRET_ACCESS_KEY }}#g" ${{ github.workspace }}/ecs-task-def.json
              sed -i "s#{{VAR_12}}#${{ secrets.AWS_REGION }}#g" ${{ github.workspace }}/ecs-task-def.json
              sed -i "s#{{VAR_13}}#${{ secrets.DOMAIN_NAME }}#g" ${{ github.workspace }}/ecs-task-def.json
    
        - name: Set up Amazon ECS action
          uses: aws-actions/amazon-ecs-render-task-definition@v1
          with:
            task-definition: ./ecs-task-def.json
            container-name: resumed-events-service
            image: ${{ steps.login-ecr.outputs.registry }}/resumed-events:${{ github.sha }}
    
        - name: Deploy to Amazon ECS service
          uses: aws-actions/amazon-ecs-deploy-task-definition@v1
          with:
            task-definition: ./ecs-task-def.json
            service: resumed-events-service
            cluster: resumed-events
      