name: Deploy to Lightsail

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Pull Latest Changes (if any)
      run: git pull origin main

    - name: Deploy Changes
      run: |
        # Assuming you have a deployment script or commands to restart your service
        # Restart your service/application if necessary
        # For example, if you're using PM2 for a Node.js application:
        # pm2 restart all
        
        npx prisma db pushname: Deploy to Lightsail

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Pull Latest Changes (if any)
      run: git pull origin main