name: Deploy to Lightsail

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: See Directory
      run: pwd && ls -la 
      
    - name: Pull Latest Changes (if any)
      run: git pull


