name: Deploy API

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/loumonthjack/resumed-events

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    environment: production
    steps:
    - name: Stall  20 seconds
      run: sudo -i 
    - name: Check Container Status
      run: cd /home/app/resumed-events
    - name: Stop PM2 Process, only if it exists
      run: sudo pm2 stop resumed-events || true
    - name: Set Git Perms
      run: sudo chmod -R u+rw /home/app/resumed-events/.git
    - name: Pull Latest Code
      run: cd /home/app/resumed-events && git pull
    - name: Start PM2 Process
      run: sudo pm2 start npm --name resumed-events -- run start:dev
