name: Deploy to Lightsail

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Use Root
      run: sudo -i
    
    - name: See Directory
      run: cd /home/app/resumed-events

    - name: Set Permissions
      run: sudo chown -R $(whoami):$(whoami) /home/app/resumed-events
      
    - name: Pull Latest Changes (if any)
      run: git pull
    
    - name: Check for Running PM2 Process
      run: pm2 stop all || true

    - name: Run PM2 Process
      run: pm2 start npm --name "resumed-events" -- start:dev
    


